---
title: "Biostat 203B Homework 1"
subtitle: Due Jan 24 @ 11:59PM
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q1. Git/GitHub

**No handwritten homework reports are accepted for this course.** We work with Git and GitHub. Efficient and abundant use of Git, e.g., frequent and well-documented commits, is an important criterion for grading your homework.

1. Apply for the [Student Developer Pack](https://education.github.com/pack) at GitHub using your UCLA email.

Done

2. Create a **private** repository `biostat-203b-2020-winter` and add `Hua-Zhou` and `juhkim111` as your collaborators with write permission.

Done

3. Top directories of the repository should be `hw1`, `hw2`, ... Maintain two branches `master` and `develop`. The `develop` branch will be your main playground, the place where you develop solution (code) to homework problems and write up report. The `master` branch will be your presentation area. Submit your homework files (R markdown file `Rmd`, `html` file converted from R markdown, all code and data sets to reproduce results) in `master` branch.

Done

4. After each homework due date, teaching assistant and instructor will check out your master branch for grading. Tag each of your homework submissions with tag names `hw1`, `hw2`, ... Tagging time will be used as your submission time. That means if you tag your `hw1` submission after deadline, penalty points will be deducted for late submission.

## Q2. Linux Shell Commands

1. This exercise (and later in this course) uses the [MIMIC-III data](https://mimic.physionet.org), a freely accessible critical care database developed by the MIT Lab for Computational Physiology. Please follow the instructions at <https://mimic.physionet.org/gettingstarted/access/> to complete the CITI `Data or Specimens Only Research` course. Show the screenshot of your completion report. 

The screen shot:??????


2. The `/home/203bdata/mimic-iii/` folder on teaching server contains data sets from MIMIC-III. See <https://mimic.physionet.org/mimictables/admissions/> for details of each table.  
    ```{bash}
    ls -l /home/203bdata/mimic-iii
    ```
Please, do **not** put these data files into Git; they are big. Also do **not** copy them into your directory. Just read from the data folder `/home/203bdata/mimic-iii` directly in following exercises. 

    Use Bash commands to answer following questions.

3. What's the output of following bash script?
    ```{bash, eval=FALSE}
    for datafile in /home/203bdata/mimic-iii/*.csv
      do
        ls $datafile
      done
    ```
The output is the file end up with "csv" in the folder called mimic-iii, whose path is /home/203bdata/mimic-iii.

Display the number of lines in each `csv` file.
the code:
```{bash}
for datafile in /home/203bdata/mimic-iii/*.csv  
  do 
    ls $datafile 
    awk 'END { print NR }' $datafile
  done
```
The number of lines in ADMISSIONS.csv is 58977;
The number of lines in CALLOUT.csv is 34500;
The number of lines in CAREGIVERS.csv is 7568;
The number of lines in CHARTEVENTS.csv is 1048576;
The number of lines in CPTEVENTS.csv is 573147;
The number of lines in DATETIMEEVENTS.csv is 4485938;
The number of lines in D_CPT.csv is 135;
The number of lines in DIAGNOSES_ICD.csv is 651048;
The number of lines in D_ICD_DIAGNOSES.csv is 14568;
The number of lines in D_ICD_PROCEDURES.csv is 3883;
The number of lines in D_ITEMS.csv is 12488;
The number of lines in D_LABITEMS.csv is 754;
The number of lines in DRGCODES.csv is 125558;
The number of lines in ICUSTAYS.csv is 61533;
The number of lines in INPUTEVENTS_CV.csv is 17527936;
The number of lines in INPUTEVENTS_MV.csv is 3618992;
The number of lines in LABEVENTS.csv is 27854056;
The number of lines in MICROBIOLOGYEVENTS.csv is 631727;
The number of lines inNOTEEVENTS.csv is 91691299;
The number of lines in OUTPUTEVENTS.csv is 4349219;
The number of lines in PATIENTS.csv is 46521;
The number of lines in PRESCRIPTIONS.csv is 4156451;
The number of lines in PROCEDUREEVENTS_MV.csv is 258067;
The number of lines in PROCEDURES_ICD.csv is 240096;
The number of lines in SERVICES.csv is 73344;
The number of lines in TRANSFERS.csv is 261898

4. -Display the first few lines of `ADMISSIONS.csv`.
The code:
```{bash}
   head /home/203bdata/mimic-iii/ADMISSIONS.csv 
```
The first few lines are:
"ROW_ID","SUBJECT_ID","HADM_ID","ADMITTIME","DISCHTIME","DEATHTIME","ADMISSION_TYPE","ADMISSION_LOCATION","DISCHARGE_LOCATION","INSURANCE","LANGUAGE","RELIGION","MARITAL_STATUS","ETHNICITY","EDREGTIME","EDOUTTIME","DIAGNOSIS","HOSPITAL_EXPIRE_FLAG","HAS_CHARTEVENTS_DATA"
21,22,165315,2196-04-09 12:26:00,2196-04-10 15:54:00,,"EMERGENCY","EMERGENCY ROOM ADMIT","DISC-TRAN CANCER/CHLDRN H","Private",,"UNOBTAINABLE","MARRIED","WHITE",2196-04-09 10:06:00,2196-04-09 13:24:00,"BENZODIAZEPINE OVERDOSE",0,1
22,23,152223,2153-09-03 07:15:00,2153-09-08 19:10:00,,"ELECTIVE","PHYS REFERRAL/NORMAL DELI","HOME HEALTH CARE","Medicare",,"CATHOLIC","MARRIED","WHITE",,,"CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS GRAFT/SDA",0,1
23,23,124321,2157-10-18 19:34:00,2157-10-25 14:00:00,,"EMERGENCY","TRANSFER FROM HOSP/EXTRAM","HOME HEALTH CARE","Medicare","ENGL","CATHOLIC","MARRIED","WHITE",,,"BRAIN MASS",0,1
24,24,161859,2139-06-06 16:14:00,2139-06-09 12:48:00,,"EMERGENCY","TRANSFER FROM HOSP/EXTRAM","HOME","Private",,"PROTESTANT QUAKER","SINGLE","WHITE",,,"INTERIOR MYOCARDIAL INFARCTION",0,1
25,25,129635,2160-11-02 02:06:00,2160-11-05 14:55:00,,"EMERGENCY","EMERGENCY ROOM ADMIT","HOME","Private",,"UNOBTAINABLE","MARRIED","WHITE",2160-11-02 01:01:00,2160-11-02 04:27:00,"ACUTE CORONARY SYNDROME",0,1
26,26,197661,2126-05-06 15:16:00,2126-05-13 15:00:00,,"EMERGENCY","TRANSFER FROM HOSP/EXTRAM","HOME","Medicare",,"CATHOLIC","SINGLE","UNKNOWN/NOT SPECIFIED",,,"V-TACH",0,1
27,27,134931,2191-11-30 22:16:00,2191-12-03 14:45:00,,"NEWBORN","PHYS REFERRAL/NORMAL DELI","HOME","Private",,"CATHOLIC",,"WHITE",,,"NEWBORN",0,1
28,28,162569,2177-09-01 07:15:00,2177-09-06 16:00:00,,"ELECTIVE","PHYS REFERRAL/NORMAL DELI","HOME HEALTH CARE","Medicare",,"CATHOLIC","MARRIED","WHITE",,,"CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS GRAFT/SDA",0,1
29,30,104557,2172-10-14 14:17:00,2172-10-19 14:37:00,,"URGENT","TRANSFER FROM HOSP/EXTRAM","HOME HEALTH CARE","Medicare",,"CATHOLIC","MARRIED","UNKNOWN/NOT SPECIFIED",,,"UNSTABLE ANGINA\CATH",0,1

-How many rows are in this data file?
The code:
```{bash}
awk 'END { print NR }' /home/203bdata/mimic-iii/ADMISSIONS.csv
```
There 58977 rows in ADMISSIONS.csv datafile.

-How many unique patients (identified by `SUBJECT_ID`) are in this data file?
The code:
```{bash}

```

-What are the possible values taken by each of the variable `INSURANCE`, `LANGUAGE`, `RELIGION`, `MARITAL_STATUS`, and `ETHNICITY`?
The code:
```{bash}

```

-How many (unique) patients are Hispanic? (Hint: combine Linux comamnds `head`, `tail`, `awk`, `uniq`, `wc`, `sort` and so on using pipe.)
The code:
```{bash}

```

## Q3. More fun with shell

1. You and your friend just have finished reading *Pride and Prejudice* by Jane Austen. Among the four main characters in the book, Elizabeth, Jane, Lydia, and Darcy, your friend thinks that Darcy was the most mentioned. You, however, are certain it was Elizabeth. Obtain the full text of the novel from <https://www.gutenberg.org/files/1342/1342.txt> and save to your local folder. 
    ```{bash, eval=FALSE}
    curl https://www.gutenberg.org/files/1342/1342.txt > pride_and_prejudice.txt
    ```
Do **not** put this text file `pride_and_prejudice.txt` in Git. Using a `for` loop, how would you tabulate the number of times each of the four characters is mentioned?
The code:
```{bash}

```


0. What's the difference between the following two commands?
    ```{bash eval=FALSE}
    echo 'hello, world' > test1.txt
    ```
    and
    ```{bash eval=FALSE}
    echo 'hello, world' >> test2.txt
    ```


0. Using your favorite text editor (e.g., `vi`), type the following and save the file as `middle.sh`:
    ```{bash eval=FALSE}
    #!/bin/sh
    # Select lines from the middle of a file.
    # Usage: bash middle.sh filename end_line num_lines
    head -n "$2" "$1" | tail -n "$3"
    ```
Using `chmod` make the file executable by the owner, and run 
    ```{bash eval=FALSE}
    ./middle.sh pride_and_prejudice.txt 20 5
    ```
Explain the output. Explain the meaning of `"$1"`, `"$2"`, and `"$3"` in this shell script. Why do we need the first line of the shell script?

## Q4. R Batch Run

In class we discussed using R to organize simulation studies. 

1. Expand the [`runSim.R`](https://ucla-biostat203b-2020winter.github.io/slides/02-linux/runSim.R) script to include arguments `seed` (random seed), `n` (sample size), `dist` (distribution) and `rep` (number of simulation replicates). When `dist="gaussian"`, generate data from standard normal; when `dist="t1"`, generate data from t-distribution with degree of freedom 1 (same as Cauchy distribution); when `dist="t5"`, generate data from t-distribution with degree of freedom 5. Calling `runSim.R` will (1) set random seed according to argument `seed`, (2) generate data according to argument `dist`, (3) compute the primed-indexed average estimator and the classical sample average estimator for each simulation replicate, (4) report the average mean squared error (MSE)
$$
  \frac{\sum_{r=1}^{\text{rep}} (\widehat \mu_r - \mu_{\text{true}})^2}{\text{rep}}
$$
for both methods.

2. Modify the [`autoSim.R`](https://ucla-biostat203b-2020winter.github.io/slides/02-linux/autoSim.R) script to run simulations with combinations of sample sizes `nVals = seq(100, 500, by=100)` and distributions `distTypes = c("gaussian", "t1", "t5")` and write output to appropriately named files. Use `rep = 50`, and `seed = 203`. 

3. Write an R script to collect simulation results from output files and print average MSEs in a table of format

| $n$ | Method   | Gaussian | $t_5$ | $t_1$ |
|-----|----------|-------|-------|----------|
| 100 | PrimeAvg |       |       |          |
| 100 | SampAvg  |       |       |          |
| 200 | PrimeAvg |       |       |          |
| 200 | SampAvg  |       |       |          |
| 300 | PrimeAvg |       |       |          |
| 300 | SampAvg  |       |       |          |
| 400 | PrimeAvg |       |       |          |
| 400 | SampAvg  |       |       |          |
| 500 | PrimeAvg |       |       |          |
| 500 | SampAvg  |       |       |          |

